sudo: required
os: linux
before_install:
  - sudo apt-get install libao-dev
  - sudo apt-get install libmpg123-dev

matrix:
  include:
    - language: cpp
      compiler:
        - g++
      script:
        - g++ -O2 -o CppPlay play.c -lao -lmpg123

    - language: c
      compiler:
        - gcc
      script:
        - gcc -O2 -o CPlay play.c -lao -lmpg123
        
